- name:  basic
  hosts: all
  gather_facts: no
  become: true
  become_user: root
  collections:
  - ibm.power_aix
  tasks:
   - name: Ensure group admin exists
     group: name=admin state=present
     
   - name: Create user costa_l
     user: name=costa_l comment="Costa Lochaitis" group=admin shell=/usr/bin/ksh generate_ssh_key=yes state=modify password=passw0rd
     
   - name: Remove file (delete file)
     file: path=/home/costa_l/.profile state=absent
     
   - name: create profile file if it doesnt exist
     file: path=/home/costa_l/.profile state=touch
     
   - name: Configure users profile
     lineinfile: path=/home/costa_l/.profile line='PS1="$(whoami)@$(hostname)(\$PWD)# "\nexport PS1\nexport EDITOR=/usr/bin/vi\nset -o vi' create=yes 
     
   - name: Change file ownership and group
     file: path=/home/costa_l/.profile owner=costa_l group=admin
     
   - name: Create user ravi
     user: name=ravi comment="Ravi Mandla" group=admin shell=/usr/bin/ksh generate_ssh_key=yes state=present uid=2000
  
   - name: Remove file (delete file)
     file: path=/home/ravi/.profile state=absent
     
   - name: create profile file if it doesnt exist
     file: path=/home/ravi/.profile state=touch
  
   - name: Configure users profile
     lineinfile: path=/home/ravi/.profile line='PS1="$(whoami)@$(hostname)(\$PWD)# "\nexport PS1\nexport EDITOR=/usr/bin/vi\nset -o vi' create=yes 
     
   - name: Change file ownership and group
     file: path=/home/ravi/.profile owner=ravi group=admin
      
   - name: Create user shiven
     user: name=shiven comment="Shiven Harrichunder" group=admin shell=/usr/bin/ksh generate_ssh_key=yes state=present uid=2001
     
   - name: Remove file (delete file)
     file: path=/home/shiven/.profile state=absent
     
   - name: create profile file if it doesnt exist
     file: path=/home/shiven/.profile state=touch
     
   - name: Configure users profile
     lineinfile: path=/home/shiven/.profile line='PS1="$(whoami)@$(hostname)(\$PWD)# "\nexport PS1\nexport EDITOR=/usr/bin/vi\nset -o vi' create=yes 
     
   - name: Change file ownership and group
     file: path=/home/shiven/.profile owner=shiven group=admin
       
   - name: Create user kishore
     user: name=kishore comment="Kishore Rampersad" group=admin shell=/usr/bin/ksh generate_ssh_key=yes state=present uid=2002
     
   - name: Remove file (delete file)
     file: path=/home/kishore/.profile state=absent
     
   - name: create profile file if it doesnt exist
     file: path=/home/kishore/.profile state=touch
     
   - name: Configure users profile
     lineinfile: path=/home/kishore/.profile line='PS1="$(whoami)@$(hostname)(\$PWD)# "\nexport PS1\nexport EDITOR=/usr/bin/vi\nset -o vi' create=yes 
     
   - name: Change file ownership and group
     file: path=/home/kishore/.profile owner=kishore group=admin
       
   - name: Create a volume group datavg
     aix_lvg: vg=datavg vg_type=scalable pp_size=128 state=present pvs=hdisk1 
     
   - name: Varyon a volume group
     aix_lvg: vg=datavg state=varyon
     
   - name: Create a logical volume of 250M
     aix_lvol: vg=datavg lv=datalv01 size=250M

   - name: Create a logical volume of 250M
     aix_lvol: vg=datavg lv=datalv02 size=250M
     
   - name: Creation of a JFS2 filesystem on a previously defined lv
     aix_filesystem: device=datalv01 filesystem=/data1 state=present fs_type=jfs2 auto_mount=yes
     
   - name: Creation of a JFS2 filesystem on a previously defined lv
     aix_filesystem: device=datalv02 filesystem=/data2 state=present fs_type=jfs2 auto_mount=yes
     
   - name: Mount filesystems
     mount: mount_dir=/dev/datalv01 mount_over_dir=/data1
     
   - name: Mount filesystems
     mount: mount_dir=/dev/datalv02 mount_over_dir=/data2
  
   - name: Add a DNS entry
     lineinfile: path=/etc/resolv.conf line='nameserver 172.30.12.50' create=yes
     
   - name: Add all hosts running this playbook to the AIX_hosts group
     add_host: name='{{ item }}' groups=AIX_hosts
     loop: "{{ ansible_play_hosts }}"
     
   #- name: Perform a cleanup of any existing alternate disk copy
   #  alt_disk: action=clean
     
   #- name: Perform an alternate disk copy of the rootvg to the smallest disk that can be selected
   #  alt_disk: disk_size_policy=minimize

  
     
 
     
  
