- name:  AIX Update
  hosts: 172.30.30.70
  gather_facts: yes
  become: true
  become_user: root
  tasks:
   - name: Check, download and install to TL 7.2.3
     suma: action=download oslevel='7200-04-00'
