- name:  "SUMA on AIX"
  hosts: all
  gather_facts: no
  become: true
  become_user: root
  remote_user: devops
  vars:
    download_dir: /suma
    download_only: False
  tasks:
  
  - name: Create file system for system updates
    aix_filesystem:
      filesystem: "{{ download_dir }}"
      size: 50G
      state: present
      vg: nimvg
      
  - name: Mount the file system (if necessary)
    aix_filesystem:
      filesystem: "{{ download_dir }}"
      state: mounted
      
  - name: Check and download required to update to SP 7.2.3.5
    suma:
      action: download
      oslevel: '7200-03-05'
      download_only: yes
      download_dir: /suma/
    when: ansible_distribution == 'AIX'
      
  #- name: Check, download and install system updates for the current oslevel of the system
  #  suma:
  #    action: download
      #oslevel: Latest
      #download_dir: /suma
      
  #- name: Check and download required to update to SP 7.2.3.5
  #  suma:
  #    action: download
  #    oslevel: '7200-03-05'
  #    download_only: yes
  #    download_dir: /suma/dl_updt_7200-03-05
  #  when: ansible_distribution == 'AIX'
   
