- name:  "SUMA on AIX"
  hosts: all
  #gather_facts: no
  become: true
  become_user: root
  remote_user: devops
  
  tasks:
   - name: Create file system for system updates
     aix_filesystem: filesystem="/suma" size=50G state=present vg=nimvg
      
   - name: Mount the file system (if necessary)
     aix_filesystem: filesystem="/suma" state=mounted 
    
   - name: Check oslevel of system
     shell: cmd="oslevel -s" when="ansible_distribution == 'AIX'" register=output
  
   
   
