- name:  "SUMA on AIX"
  hosts: all
  gather_facts: no
  become: true
  become_user: root
  remote_user: devops
  vars:
    download_dir: /suma
    download_only: False
  tasks:
  
  - name: Create file system for system updates
    aix_filesystem:
      filesystem: "{{ download_dir }}"
      size: 50G
      state: present
      vg: nimvg
   
