- name:  "SUMA on AIX"
  hosts: all
  gather_facts: no
  become: true
  become_user: root
  remote_user: devops
  
- name: Check, download and install system updates for the current oslevel of the system
  suma:
    action: download
    oslevel: Latest
    download_dir: /suma
