- name:  "SUMA on AIX"
  hosts: all
  gather_facts: no
  become: true
  become_user: root
  remote_user: devops
  vars:
    download_dir: /suma
    download_only: False
  
  tasks:
  - name: Check oslevel of system
    shell: "oslevel -s"
    when: ansible_distribution == 'AIX'
    register: output
  - debug: var=output

  - name: Create file system for system updates
    aix_filesystem:
      filesystem: "{{ download_dir }}"
      size: 50G
      state: present
      vg: nimvg

  - name: Mount the file system (if necessary)
    aix_filesystem:
      filesystem: "{{ download_dir }}"
      state: mounted 

  - name: Check, download and install system updates for the current oslevel of the system
    suma:
      action: download
      oslevel: Latest
      download_dir: "{{ download_dir }}"
