- name: VIOS  
  hosts: all
  gather_facts: no
  user: devops 

  tasks:
- name: Creating NFS filesystem from nfshost.
  aix_filesystem: device=/backup nfs_server=172.30.30.233 filesystem=/backup state=present
