- name: basic
  hosts: all
  gather_facts: no
  become: true
  become_user: padmin
  tasks:
- name: Perform a health check on dual VIOSes 
  ibm.power_aix.nim_vios_hc: targets=FWVios1 action=health_check
