- name: VIOS  
  hosts: 172.30.30.110
  gather_facts: no
  user: devops 
  
  tasks:
   - name: Generate an mksysb backup to /home/padmin/backup.mksysb
     ibm.power_vios.backupios:
       file: /home/padmin/backup.mksysb
       mksysb: yes
       savemedialib: no
       savevgstruct: no
