---
- name: "YuM Check-Update"
  hosts: all
  gather_facts: no
  user: devops
  vars:
    name: '*'
    state: latest
    exclude: kernel*
  tasks:

  - name: Upgrade packages, excluding kernel related packages
    yum:
      name: "{{ name }}"
      state: "{{ state }}"
      exclude: "{{ exclude }}"
      use_backend: yum3

    register: output
  - debug: var=output
